services:
  - type: web
    name: venocare
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn venocare.wsgi:application
    envVars:
      - key: DJANGO_SECRET_KEY
        generateValue: true
      - key: DATABASE_URL
        fromDatabase:
          name: venocare-db
          property: connectionString
