# Generated by Django 5.1.6 on 2025-05-27 14:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_remove_uploadedimage_stage_detected_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='uploadedimage',
            name='stage',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='uploadedimage',
            name='user',
            field=models.ForeignKey(default=3, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
