# Generated by Django 5.1.6 on 2025-05-28 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_uploadedimage_stage_alter_uploadedimage_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='recoveryplan',
            name='stage',
            field=models.CharField(default='unknown', max_length=50),
            preserve_default=False,
        ),
    ]
