# Generated by Django 5.1.6 on 2025-06-02 07:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_recoveryplan_stage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('patient', 'Patient'), ('doctor', 'Doctor'), ('caregiver', 'Caregiver')], default='patient', max_length=10),
        ),
    ]
