# Generated by Django 5.1.6 on 2025-06-03 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_user_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='uploadedimage',
            name='rvcss_score',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
