# Generated by Django 5.1.6 on 2025-06-04 03:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_uploadedimage_rvcss_score'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recoveryplan',
            name='stage',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
